spring:
  profiles:
    active: -dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: cloud-configclient1
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓。
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群
      #defaultZone: http://localhost:7001/eureka  #单机帮
  instance:
    instance-id: SPRING-CLOUD-config-client
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: cloud-configclient1
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓。
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群
      #defaultZone: http://localhost:7001/eureka  #单机帮
  instance:
    instance-id: SPRING-CLOUD-config-client